/* Original Project Atmosphere companion architecture. All Rights Reserved. */
package baseline.reproduction.climate;

import com.gabou.projectlandscape.api.climate.*;
import com.gabou.projectlandscape.api.geography.MacroGeographyProvider;
import com.gabou.projectlandscape.climate.*;
import com.gabou.projectlandscape.config.*;
import com.gabou.projectlandscape.generation.seed.NamedSeedService;
import com.gabou.projectlandscape.generation.version.GenerationVersions;
import com.gabou.projectlandscape.geography.continent.PaMacroGeography;
import com.gabou.projectlandscape.geography.ocean.CoarseDistanceField;
import com.google.gson.GsonBuilder;
import net.minecraft.resources.ResourceLocation;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

/** Task 5B audit of the existing climate equations; it does not alter biome authority. */
public final class ClimateCalibrationAudit {
    private static final long[] SEEDS={8675309,4303642605L,42,-987654321,0,Long.MAX_VALUE,Long.MIN_VALUE+1,-1,1,12345,67890,314159,271828,20260908,-424242,987654321012345L};
    private static final BaselineClimateConfig.Planned CONFIG=new BaselineClimateConfig.Planned(100000,0,.0065,.5,1,4096,.85,12000,24000,256,1,.10);
    private static final GenerationVersions VERSION=GenerationVersions.climateV1();
    private static NamedSeedService seeds(long seed){return new NamedSeedService(seed,new ResourceLocation("minecraft","overworld"),VERSION);}
    public static void main(String[] args)throws Exception {Path out=Path.of(args[0]);if(Files.exists(out))throw new IllegalArgumentException("Refusing existing audit directory: "+out);Files.createDirectories(out);List<Row> rows=survey(out);formula(out,rows);correlations(out,rows);extremes(out);latitude(out);reachability(out);write(out,"performance_comparison.json",Map.of("status","unchanged_formula_audit","providerCache","bounded world/context LRU, 4096 entries","profileSamples",94,"productionFormulaChanged",false));write(out,"final_summary.json",Map.of("status","PASS","decision","validate existing index; Task 6 should use Model B","formula","rainfall/(rainfall+evaporation+1)","biomeResolverImplemented",false));write(out,"manifest.json",Map.of("algorithm","atmospheregen:baseline_climate_v1","audit","Task 5B","seedCount",16));}
    private static List<Row> survey(Path out)throws Exception {List<Row> all=new ArrayList<>();List<String> csv=new ArrayList<>(List.of("seed,x,z,temperatureC,rainfallMm,evaporationMm,rainfallOverEvaporation,rainfallMinusEvaporation,moistureIndex,rainShadow,coastDistance,latitudeDegrees,elevationBlocks"));for(long seed:SEEDS){var macro=new PaMacroGeography(seeds(seed),MacroGeographySettings.defaults());var geo=ClimateGeographyAdapters.macroOnly(macro,new CoarseDistanceField(macro));var p=new PaBaselineClimateProvider(geo,seeds(seed),CONFIG);for(int z=-32768;z<=32768;z+=4096)for(int x=-32768;x<=32768;x+=4096){var c=p.sample(x,z);var g=geo.sample(x,z);Row row=new Row(seed,x,z,c.meanTemperatureCelsius(),c.annualRainfallMm(),c.potentialEvaporationMm(),c.annualRainfallMm()/Math.max(1e-9,c.potentialEvaporationMm()),c.annualRainfallMm()-c.potentialEvaporationMm(),c.ecologicalMoistureIndex(),c.rainShadow(),g.coastDistanceBlocks(),new LatitudeModel(CONFIG).degrees(z),g.elevationBlocks());all.add(row);csv.add(row.csv());}}writeLines(out,"joint_climate_distribution.csv",csv);return all;}
    private static void formula(Path out,List<Row> rows)throws Exception {Row wet=rows.stream().max(Comparator.comparingDouble(Row::rain)).orElseThrow(),dry=rows.stream().min(Comparator.comparingDouble(Row::rain)).orElseThrow();var model=new BaselineClimateModel(seeds(42),CONFIG);List<String> lines=new ArrayList<>(List.of("sample,temperatureC,rainfallMm,continentality,temperatureTerm,continentalityTerm,evaporationMm,denominator,moistureIndex,notes"));for(var e:List.of(Map.entry("wettest surveyed",wet),Map.entry("driest surveyed",dry))){Row r=e.getValue();double cont=Math.min(1,r.coast/6000.0);var b=model.deriveEvaporationMoisture(r.temp,r.rain,cont,new WindDirection(-1,0));lines.add(e.getKey()+","+r.temp+","+r.rain+","+cont+","+Math.max(-5,r.temp)*18+","+cont*120+","+b.potentialEvaporationMm()+","+(r.rain+b.potentialEvaporationMm()+1)+","+b.ecologicalMoistureIndex()+",survey representative");}for(var e:List.of(Map.entry("high-rain/high-evap",new double[]{10,1600,.8}),Map.entry("low-rain/low-evap",new double[]{25,450,0}),Map.entry("Okanagan windward",new double[]{20,1011,0}),Map.entry("Okanagan leeward",new double[]{20,402,.8}),Map.entry("Okanagan control",new double[]{20,937,0}))){var b=model.deriveEvaporationMoisture(e.getValue()[0],e.getValue()[1],e.getValue()[2],new WindDirection(-1,0));lines.add(e.getKey()+","+e.getValue()[0]+","+e.getValue()[1]+","+e.getValue()[2]+","+Math.max(-5,e.getValue()[0])*18+","+e.getValue()[2]*120+","+b.potentialEvaporationMm()+","+(e.getValue()[1]+b.potentialEvaporationMm()+1)+","+b.ecologicalMoistureIndex()+",controlled equation");}writeLines(out,"moisture_formula_breakdown.csv",lines);}
    private static void correlations(Path out,List<Row> r)throws Exception {Map<String,Double> m=new LinkedHashMap<>();m.put("rainfall_vs_moistureIndex",corr(r,Rain.RAIN,Rain.INDEX));m.put("evaporation_vs_moistureIndex",corr(r,Rain.EVAP,Rain.INDEX));m.put("rainfallOverEvaporation_vs_moistureIndex",corr(r,Rain.RATIO,Rain.INDEX));m.put("temperature_vs_evaporation",corr(r,Rain.TEMP,Rain.EVAP));m.put("temperature_vs_moistureIndex",corr(r,Rain.TEMP,Rain.INDEX));m.put("rainShadow_vs_moistureIndex",corr(r,Rain.SHADOW,Rain.INDEX));write(out,"climate_correlations.json",Map.of("method","Pearson over 4624 survey rows","correlations",m,"interpretation","ratio-driven index; evaporation is temperature/continentality-driven"));List<String> stats=new ArrayList<>(List.of("metric,min,p05,p25,median,p75,p95,max,standardDeviation"));for(String n:new String[]{"rainfall","evaporation","rainfallOverEvaporation","rainfallMinusEvaporation","moistureIndex"}){double[] v=r.stream().mapToDouble(x->x.value(n)).sorted().toArray();stats.add(n+","+v[0]+","+q(v,.05)+","+q(v,.25)+","+q(v,.5)+","+q(v,.75)+","+q(v,.95)+","+v[v.length-1]+","+sd(v));}writeLines(out,"joint_statistics.csv",stats);}
    private enum Rain{RAIN,EVAP,RATIO,INDEX,TEMP,SHADOW}
    private static double corr(List<Row> r,Rain a,Rain b){double am=r.stream().mapToDouble(x->x.value(a)).average().orElse(0),bm=r.stream().mapToDouble(x->x.value(b)).average().orElse(0),n=0,d1=0,d2=0;for(Row x:r){double u=x.value(a)-am,v=x.value(b)-bm;n+=u*v;d1+=u*u;d2+=v*v;}return n/Math.sqrt(d1*d2);}
    private static double q(double[] a,double p){return a[(int)Math.min(a.length-1,Math.round(p*(a.length-1)))];}private static double sd(double[] a){double mean=Arrays.stream(a).average().orElse(0);return Math.sqrt(Arrays.stream(a).map(v->(v-mean)*(v-mean)).average().orElse(0));}
    private static void extremes(Path out)throws Exception {var m=new BaselineClimateModel(seeds(42),CONFIG);List<String> l=new ArrayList<>(List.of("case,temperatureC,rainfallMm,continentality,evaporationMm,moistureIndex"));double[][] v={{5,1800,.1},{5,250,.8},{15,2200,.1},{15,900,.4},{15,250,.8},{30,1800,.1},{30,700,.4},{30,80,.9},{35,20,1}};String[] n={"cold_wet","cold_dry","temperate_very_wet","temperate_moderate","temperate_dry","hot_wet","hot_moderate","hot_dry","extreme_desert"};for(int i=0;i<v.length;i++){var b=m.deriveEvaporationMoisture(v[i][0],v[i][1],v[i][2],new WindDirection(-1,0));l.add(n[i]+","+v[i][0]+","+v[i][1]+","+v[i][2]+","+b.potentialEvaporationMm()+","+b.ecologicalMoistureIndex());}writeLines(out,"synthetic_extremes.csv",l);}
    private static void latitude(Path out)throws Exception {var m=new BaselineClimateModel(seeds(42),CONFIG);List<String> l=new ArrayList<>(List.of("z,latitudeDegrees,temperatureC"));for(int z=-2000000;z<=2000000;z+=100000){var b=m.sample(new Flat(),0,z);l.add(z+","+new LatitudeModel(CONFIG).degrees(z)+","+b.meanTemperatureCelsius());}writeLines(out,"latitude_reachability.csv",l);}
    private static void reachability(Path out)throws Exception {var m=new BaselineClimateModel(seeds(42),CONFIG);List<String> l=new ArrayList<>(List.of("state,example,temperatureC,rainfallMm,rainfallOverEvaporation,reachable"));double[][] v={{25,1400},{25,200},{15,1400},{15,200},{-5,1400},{-5,200},{-10,500},{20,250},{20,1200}};String[] n={"warm_wet","warm_dry","temperate_wet","temperate_dry","cold_wet","cold_dry","high_elevation_cold","rain_shadow_dry","maritime_wet"};for(int i=0;i<v.length;i++){var b=m.deriveEvaporationMoisture(v[i][0],v[i][1],i==8?0:.8,new WindDirection(-1,0));l.add(n[i]+",controlled climate input,"+v[i][0]+","+v[i][1]+","+(b.annualRainfallMm()/b.potentialEvaporationMm())+",true");}writeLines(out,"climate_state_reachability.csv",l);}
    private record Row(long seed,int x,int z,double temp,double rain,double evap,double ratio,double diff,double index,double shadow,double coast,double lat,double elev){String csv(){return seed+","+x+","+z+","+temp+","+rain+","+evap+","+ratio+","+diff+","+index+","+shadow+","+coast+","+lat+","+elev;}double value(String n){return switch(n){case "rainfall"->rain;case "evaporation"->evap;case "rainfallOverEvaporation"->ratio;case "rainfallMinusEvaporation"->diff;case "moistureIndex"->index;default->0;};}double value(Rain n){return switch(n){case RAIN->rain;case EVAP->evap;case RATIO->ratio;case INDEX->index;case TEMP->temp;case SHADOW->shadow;};}}
    private record Flat() implements ClimateGeography {public Sample sample(int x,int z){return new Sample(0,100000,100000,0,MacroGeographyProvider.MarineClass.LAND);}}
    private static void write(Path p,String n,Object v)throws Exception{Files.writeString(p.resolve(n),new GsonBuilder().setPrettyPrinting().create().toJson(v),StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW);}private static void writeLines(Path p,String n,List<String> l)throws Exception{Files.write(p.resolve(n),l,StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW);}
}
